### ISSUE TITLE
Add `isIP` to opts

### ISSUE THREAD

**Issue by xuset** [mafintosh/k-rpc-socket#4]
Hi there!

I'm using `socket` instance that uses 160 bit hex IDs for addressing peers instead of IPs. The problem that I'm having is that when RPC#query is called, it sees that the ID is not an IP so it tries to resolve it which fails. It would be awesome If I could specify my own `isIP` function so I can bypass the check. I hope you think this is a worthwhile feature! If you want I can submit a PR for this?

My end goal with the project I'm working on is to get this package running in the browser.

**Comment by mafintosh** [comment]
sure. open a PR that add that and i'll merge it :tada:

**Comment by feross** [comment]
Fixed by #5
