### ISSUE TITLE
Consider checking/sanitizing messages 

### ISSUE THREAD

**Issue by Ivshti** [mafintosh/k-rpc-socket#9]
Over prolonged usage of this along with bittorrent-dht, this happens:

```
Cannot read property 'y' of null TypeError: Cannot read property 'y' of null
    at Socket.onmessage (/z/s/node_modules/k-rpc-socket/index.js:66:23)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:550:8)
```

Quick check of the source code reveals that this module makes a lot of assumptions about the contents of `message`. So corrupt messages can easily cause JS exceptions and therefore be used for denial of service attacks

If I'm not missing any reason this SHOULD be that way (e.g. messages should be sanitized somewhere else), then I should make a PR?

**Comment by feross** [comment]
@Ivshti Thanks for the report. I don't think we need to do a separate validation step to fix this. 

It turns out that `bencode.decode()` can sometimes return `null`. We were assuming that it either returns an object or throws an exception. But as you can see here, `null` can be returned too:

```
> bencode.decode(Buffer.alloc(0))
null
> bencode.decode(Buffer.alloc(1))
Error: Invalid data: Missing delimiter ":" [0x3a]
```

**Comment by feross** [comment]
PR to fix this: https://github.com/mafintosh/k-rpc-socket/pull/10
